apiVersion: 1

datasources:
  - name: reg_ml_demo
    uid: aei784ojzbrpca
    type: grafana-postgresql-datasource   # <— use the new plugin id explicitly
    access: proxy
    url: postgres:5432
    user: reg_ml_demo
    isDefault: true
    jsonData:
      database: reg_ml_demo                    # <— MUST live here for this plugin
      sslmode: disable
      timescaledb: true
      postgresVersion: 1600               # optional but recommended for PG16
    secureJsonData:
      password: raptorblingx_demo

  - name: Smart_Plug
    uid: eedpsv3vt1fy8c
    type: grafana-mqtt-datasource
    access: proxy
    jsonData:
      uri: tcp://89.252.166.188:2010
      username: raptorblingx
      tlsSkipVerify: true
    secureJsonData:
      password: raptorblingx
